backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  squash_merges: true

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "documents"
        label: "Risorse"
        file: "content/pages/risorse.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "createdAt", widget: "datetime" }
          - { label: "Update Date", name: "updatedAt", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
      - name: "contacts"
        label: "Contatti"
        file: "content/pages/contatti.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "createdAt", widget: "datetime" }
          - { label: "Update Date", name: "updatedAt", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
      - name: "essere-judge"
        label: "Essere Judge"
        file: "content/pages/essere-judge.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "createdAt", widget: "datetime" }
          - { label: "Update Date", name: "updatedAt", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "createdAt", widget: "datetime" }
      - { label: "Update Date", name: "updatedAt", widget: "datetime" }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "judges"
    label: "Judges"
    folder: "content/judges"
    create: true
    slug: "{{nickname}}"
    fields:
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Nickname", name: "nickname", widget: "string" }
      - { label: "Publish Date", name: "createdAt", widget: "datetime" }
      - { label: "Update Date", name: "updatedAt", widget: "datetime" }
      - { label: "Bio", name: "bio", widget: "string" }
      # - {label: "Body", name: "body", widget: "markdown"}

  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "createdAt", widget: "datetime" }
      - { label: "Update Date", name: "updatedAt", widget: "datetime" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "judges"
        search_fields: ["firstName", "lastName", "nickname"]
        value_field: "{{nickname}}"
        display_fields: ["firstName", "lastName"]
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
      - {label: "Abstract", name: "abstract", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
